name: upaychat
description: Upaychat Financial App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.8+14

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_paystack: ^1.0.7
  shared_preferences: ^2.0.7
  http: ^0.13.3
  fluttertoast: ^8.0.8
  image_picker: ^0.8.3+3
  image_cropper: ^3.0.0
  connectivity: ^3.0.6
  flutter_spinkit: ^5.1.0
  pin_input_text_field: ^4.1.0
  timeago: ^3.1.0
  # international_phone_input: ^1.0.4
  intl_phone_field: ^3.1.0
  dotted_line: ^3.0.0
  eventhandler: ^1.0.4
  flutter_credit_card: ^3.0.4
  url_launcher: ^6.1.10
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.1
  flutter_local_notifications: ^14.0.0+1
  intl: ^0.17.0
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  firebase_auth: ^4.0.1
  badges: ^3.1.1
  flutter_slidable: ^2.0.0
  firebase_database: ^10.0.1
  pin_code_fields: ^7.3.0
  pdf: ^3.6.0
  path_provider: ^2.0.4
  touchable_opacity: ^1.2.0
  file_picker: ^5.2.1
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_vector_icons: ^2.0.0
  cupertino_date_textbox: ^1.0.1
  flutter_image_compress: ^1.1.3
  gallery_saver: ^2.3.2
  libphonenumber: ^2.0.2
  flip_card: ^0.6.0
  flutter_spinbox: ^0.10.0
  collection: ^1.16.0
  flutter_share: ^2.0.0
  drop_down_list: ^0.0.4
  form_builder_phone_field: ^1.3.0
  textfield_search: ^0.10.0
  flutterwave_standard: ^1.0.5
  uuid: ^3.0.6
  isw_mobile_sdk: ^1.1.1
  webview_flutter: ^3.0.4
  flutter_tawk: ^0.1.0
  flutter_native_splash: ^2.2.15
  platform_device_id: ^1.0.1
  flutter_config: ^2.0.0
  store_redirect: ^2.0.1
  device_name: ^0.0.4
  device_info_plus: ^8.0.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  flutter_hooks: ^0.18.6
  rounded_modal: ^1.0.1
  geocoding: ^2.1.0
  syncfusion_flutter_maps: ^21.1.41
  google_maps_webservice: ^0.0.19
  flutter_polyline_points: ^1.0.0
  workmanager: ^0.5.1
  cloud_firestore: ^4.5.2
  flutter_background_service: ^3.0.1
  image: ^4.0.15
  sliding_up_panel: ^2.0.0+1
  custom_marker: ^1.0.0
  apptex_chat: ^1.2.2
  google_maps_place_picker_mb: ^3.0.1
  flutter_google_places_hoc081098: ^1.2.0
  google_api_headers: ^1.5.0+1
  google_places_flutter: ^2.0.5
  wakelock: ^0.4.0
  flutter_ringtone_player: ^3.2.0
  vibration: ^1.7.7
  system_alert_window: ^1.2.1
  get: ^4.6.5
  alarm: ^1.0.5
  share_plus: ^7.0.2
  firebase_dynamic_links: ^5.3.3
  loadmore: ^2.1.0
  flutter_pagewise: ^2.0.4
  infinite_scroll_pagination: ^3.2.0
  flutter_svg: ^1.1.6
  loader_overlay: ^2.3.2
  dropdown_textfield: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/ios_logo.jpg
    - assets/alarm.wav
    - assets/nokia.mp3
    - assets/ic_cashout.svg
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Doomsday
      fonts:
        - asset: fonts/LayarBahtera Doomsday.ttf
        - asset: fonts/LayarBahtera Doomsday Light.ttf
        - asset: fonts/LayarBahtera Doomsday Extended.ttf
        - asset: fonts/LayarBahtera Doomsday Extended Light.ttf
        - asset: fonts/LayarBahtera Doomsday Extended Bold.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed Light.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed Bold.ttf
        - asset: fonts/LayarBahtera Doomsday Bold.ttf
        - asset: fonts/Layar Bahtera Doomsday Light Italic.ttf
        - asset: fonts/Layar Bahtera Doomsday Italic.ttf
        - asset: fonts/Layar Bahtera Doomsday Bold Italic.ttf
flutter_native_splash:
  color: "#E8FCE8"
  image: assets/logo.png
  image_ios: assets/logo.png
  android_12:
    color: "#E8FCE8"
    image: assets/splash_logo.png
